{
	'PrintConfigAtStartUp': 1,
	'DirectoryFile':        ['index', 'Main'],
	'ExtensionsToIgnore':	['.pyc', '.pyo', '.py~', '.bak'],
	'LogActivity':          0,
	'ActivityLogFilename':  'Logs/Activity.csv',
	'ActivityLogColumns':   ['request.remoteAddress', 'request.method', 'request.uri', 'response.size', 'servlet.name', 'request.timeStamp', 'transaction.duration', 'transaction.errorOccurred'],

	# Error handling
	'ShowDebugInfoOnErrors':  1,
	'UserErrorMessage':       'The site is having technical difficulties with this page. An error has been logged, and the problem will be fixed as soon as possible. Sorry!',
	'ErrorLogFilename':       'Logs/Errors.csv',
	'SaveErrorMessages':      1,
	'ErrorMessagesDir':       'ErrorMsgs',
	'EmailErrors':            0, # be sure to review the following settings when enabling error e-mails
	'ErrorEmailServer':       'mail.-.com',
	'ErrorEmailHeaders':      { 'From':         '-@-.com',
		                        'To':           ['-@-.com'],
		                        'Reply-to':     '-@-.com',
		                        'Content-type': 'text/html',
		                        'Subject':      'Error',
	                          },
	'Contexts':               {'default':       'Examples',
							   'Examples':      'Examples',
							   'Documentation': 'Documentation',
							   'Testing':       'Testing',
							  },
	'SessionTimeout':         60*60, # seconds
}
